#@apiURL=https://user-service-api-user-service.2.rahtiapp.fi
@apiURL=http://localhost:8000
#get token from your .env
@token={{$dotenv TOKEN}}

###
GET {{apiURL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{apiURL}}/users
Content-Type: application/json

###
GET {{apiURL}}/users
Content-Type: application/json
Authorization: Beer {{token}}

###
GET {{apiURL}}/users/15
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{apiURL}}/users
Content-Type: application/json

{
    "name": "Lollo",
    "email": "lollo@test.com",
    "phone": "11827323252436",
    "dob": "1998-01-01T00:00:00Z",
    "password": "lollo123!"
}

###
POST {{apiURL}}/login
Content-Type: application/json

{
    "email": "lollo@test.com",
    "password": "lollo123!"
}

###
PATCH {{apiURL}}/users
Content-Type: application/json 

{
    "id": "4",
    "name": "ErikNY",
    "email": "eriksnyaepost@erik.com",
    "phone": "66778899",
    "dob": "1993-01-01T00:00:00Z",
    "purchases": 5,
    "updatedAt": "2025-01-30T11:50:07.975000Z"
}

###
DELETE {{apiURL}}/users/3
Content-Type: application/json 
